language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
before_script:
  - 'git clone git://github.com/puppetlabs/puppetlabs-stdlib.git spec/fixtures/modules/stdlib'
script: "rake spec"
env:
  - PUPPET_VERSION=2.6.12
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.7.9
  - PUPPET_VERSION=3.1.0
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.12
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.6.12